---
- name: Deploy Docker Container
  hosts: web
  become: yes
  
  tasks:
    - name: Docker paketinin kurulu olduğundan emin ol
      apt:
        name: docker.io
        state: present
        update_cache: yes

    - name: Docker servisinin çalışır ve aktif durumda olduğundan emin ol
      systemd:
        name: docker
        state: started
        enabled: yes

    - name: Docker Hub'dan en son imajı çek (pull)
      shell: docker pull YOUR_DOCKERHUB_USERNAME/myapp:latest

    - name: Eğer çalışıyorsa eski 'myapp' container'ını durdur
      shell: docker stop myapp
      ignore_errors: yes

    - name: Eski 'myapp' container'ını sistemden sil
      shell: docker rm myapp
      ignore_errors: yes

    - name: Yeni container'ı çalıştır
      shell: docker run -d --restart unless-stopped -p 80:5000 --name myapp YOUR_DOCKERHUB_USERNAME/myapp:latest
